<?php

/**
 * @file
 * Module file for unical_client module.
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function unical_client_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.unical_client':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (! \Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = array('settings' => $settings);
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 *
 * @see hook_theme()
 */
function unical_client_theme($existing, $type, $theme, $path) {
  return [
    'calendar' => [
      'variables' => [
        'site_id'   => NULL,
        'site_url'   => NULL,
        'addevent_id'   => NULL,
        'base' => NULL
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_page().
 *
 * Adds js to the page.
 */
function unical_client_preprocess_page(&$variables) {
  $variables['#attached']['library'][] =  'unical_client/unical';
}



/**
 * Implements hook_library_info_alter().
 *
 * Dynamically adds css/js to libraries.yml, so we may use the input fields of the module.
 */
function unical_client_library_info_alter(&$libraries) {
  $unical_client_fields = \Drupal::config('unical_client.settings');
  // Get config fields, so we may modify css/js
  $url = $unical_client_fields->get('unical_client.site_url');
  $unical_modules_path = $unical_client_fields->get('unical_client.unical_modules_path');
  $use_stock_css = $unical_client_fields->get('unical_client.use_stock_css');
  $use_custom_css = $unical_client_fields->get('unical_client.use_custom_css');

  if (isset($url)) {
    if (isset($libraries['unical'])) {
      $libraries['unical']['js'][$url . $unical_modules_path . '/unical/app/build/unical.js'] = array('type' => 'external');
      if ($use_stock_css) {
        $libraries['unical']['css']['theme'][$url . $unical_modules_path . '/unical/assets/css/styles.css'] = array('type' => 'external');
      }
      if ($use_custom_css) {
        $libraries['unical']['css']['theme'][$url . $unical_modules_path . '/unical_styles/style.css'] = array('type' => 'external');
      }
    }
  }

}
