<?php

/**
 * @file
 * Implements various hooks and functions to run the unical_client module.
 */

/**
 * Implements hook_help().
 */
 function unical_client_help($path, $arg) {
  switch ($path) {
    case 'admin/help#unical_client':

      $filepath = dirname(__FILE__) . '/README.md';
      if (file_exists($filepath)) {
        $readme = file_get_contents($filepath);
      }
      else {
        $filepath = dirname(__FILE__) . '/README.txt';
        if (file_exists($filepath)) {
          $readme = file_get_contents($filepath);
        }
      }
      if (!isset($readme)) {
        return NULL;
      }
      if (module_exists('markdown')) {
        $filters = module_invoke('markdown', 'filter_info');
        $info = $filters['filter_markdown'];

        if (function_exists($info['process callback'])) {
          $output = $info['process callback']($readme, NULL);
        }
        else {
          $output = '<pre>' . $readme . '</pre>';
        }
      }
      else {
        $output = '<pre>' . $readme . '</pre>';
      }

      return $output;
  }
 }

/**
 * Implements hook_init().
 */
function unical_client_init() {

  // Get API URL setting.
  $site_url = variable_get('unical_client_settings_site_url');
  $site_id = variable_get('unical_client_settings_site_id');
  $addthis_id = variable_get('unical_client_settings_addevent_id');

  // JS Variables.
  $settings = array(
    'site_url' => $site_url,
    'site_id' => $site_id,
    'addevent_id' => $addthis_id,
  );
  drupal_add_js(array('unical_client_variables' => $settings), 'setting');

  // Unical API JS.
  drupal_add_js($site_url . 'sites/all/modules/unical/app/build/unical.js', 'file', 'footer');

  // Fonts.
  drupal_add_css('https://fonts.googleapis.com/css?family=Open+Sans:400,700', 'external');
  drupal_add_css('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css', 'external');

  // CSS.
  drupal_add_css($site_url . 'sites/all/modules/unical/assets/css/styles.css', 'external');
}

/**
 * Implements hook_menu().
 */
function unical_client_menu() {

  $items = array();

  $items['calendar'] = array(
    'title' => 'Calendar',
    'page callback' => 'unical_client_get',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/services/unical_client'] = array(
    'title' => 'UniCal embed settings',
    'description' => 'Configuration for UniCal embed',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('unical_client_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_form().
 */
function unical_client_form($form, &$form_state) {

  $form['some_text'] = array(
    '#markup' => '
    <p>This page allows you to define the settings that will control your rendering of the <a href="http://idfive.com">UniCal</a> custom Calendar. Your site administrator should provide you with the site URL of the mothership site, and your particular Site ID, which will do the work of pulling your custom configurations.</p>
    <ul>
    <li>Your calendar will now be viewable at <a href="/calendar">/calendar</a>.</li>
    <li><a href="/admin/config/search/path/add">Add a local path alias</a> to change the default <a href="/calendar">/calendar</a> link, if you choose.</li>
    </ul>
    <p>Contact your site administrator (who gave you the Site ID) If further customizations are required.</p>
    ',
  );

  // General settings.
  $form['unical_client_settings'] = array(
    '#type' => 'fieldset',
    '#title' => 'Settings',
  );

  // URL of the API.
  $form['unical_client_settings']['unical_client_settings_site_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Site URL'),
    '#default_value' => variable_get('unical_client_settings_site_url', ''),
    '#size' => 100,
    '#maxlength' => 255,
    '#description' => t('URL of main UniCal calendar website'),
    '#required' => TRUE,
  );

  // Site ID.
  $form['unical_client_settings']['unical_client_settings_site_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Site ID'),
    '#default_value' => variable_get('unical_client_settings_site_id', ''),
    '#size' => 5,
    '#maxlength' => 10,
    '#description' => t('ID of the site node'),
    '#required' => TRUE,
  );

  // addevent.com ID
  $form['unical_client_settings']['unical_client_settings_addevent_id'] = array(
    '#type' => 'textfield',
    '#title' => t('addevent.com ID'),
    '#default_value' => variable_get('unical_client_settings_addevent_id', ''),
    '#size' => 50,
    '#maxlength' => 100,
    '#description' => t('ID for paid addevent.com plans'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Function for above hook_menu().
 */
function unical_client_theme() {

  return array(
    'unical_client_calendar' => array(
      'template' => 'calendar',
    ),
  );
}

/**
 * Function for above hook_menu().
 */
function unical_client_get($page = 0) {

  // Load the template.
  return theme('unical_client_calendar');
}

/**
 * Preprocesses the wrapping HTML.
 *
 * Add base tag to allow ng app tu use html5mode urls. (no #)
 */
 function unical_client_preprocess_html(&$vars) {
   
   // Only on non admin paths
   if (!path_is_admin(current_path())) {
     
     if(drupal_is_front_page()) {
       $baseUrl = '/';
     } else {
       $baseUrl = '/' . drupal_get_path_alias(current_path()) . '/';
       
       //Replacement patterns
       $patterns = array();
       $patterns[0] = '/event\/([0-9]+)\/([a-z0-9-]+)*\/?/';
       $patterns[1] = '/submit-event\/?/';

       //Regular expression to remove any event URL params
       $baseUrl = preg_replace($patterns, '', $baseUrl);
     }
     
     $meta_fragment = array(
       '#type' => 'html_tag',
       '#tag' => 'base',
       '#attributes' => array(
         'href' => $baseUrl
       )
     );
     // Add header meta tag for IE to head
     drupal_add_html_head($meta_fragment, 'meta_fragment');
   }
 }
